"""initial schema

Revision ID: 56f1e41b5d4c
Revises:
Create Date: 2026-04-23 17:33:50.367620

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56f1e41b5d4c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('session_duration', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('session_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_phone_id', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_access_token', sa.Text(), nullable=True),
    sa.Column('whatsapp_connected_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('whatsapp_token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professionals_email'), 'professionals', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_logs_professional_id'), 'audit_logs', ['professional_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='chk_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='chk_time_range'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_slots_professional_id', 'availability_slots', ['professional_id'], unique=False)
    op.create_table('blocked_periods',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notify_clients', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('end_datetime > start_datetime', name='chk_blocked_period_range'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blocked_periods_professional_id', 'blocked_periods', ['professional_id'], unique=False)
    op.create_index('idx_blocked_periods_range', 'blocked_periods', ['professional_id', 'start_datetime', 'end_datetime'], unique=False)
    op.create_table('clients',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('whatsapp_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('email_opt_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_phone', 'clients', ['professional_id', 'phone'], unique=False)
    op.create_index('idx_clients_professional_id', 'clients', ['professional_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_professional_id'), 'refresh_tokens', ['professional_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('recurrences',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('session_duration', sa.Integer(), nullable=False),
    sa.Column('session_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly', 'biweekly', 'monthly')", name='chk_recurrence_frequency'),
    sa.CheckConstraint('day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6', name='chk_recurrence_day_of_week'),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='chk_recurrence_end_date'),
    sa.CheckConstraint('interval > 0', name='chk_recurrence_interval'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurrences_client_id', 'recurrences', ['client_id'], unique=False)
    op.create_index('idx_recurrences_professional_id', 'recurrences', ['professional_id'], unique=False)
    op.create_table('whatsapp_conversations',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('mode', sa.String(length=20), server_default=sa.text("'ai'"), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_message_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("mode IN ('ai', 'handoff')", name='chk_conversation_mode'),
    sa.CheckConstraint("status IN ('active', 'resolved', 'waiting_professional')", name='chk_conversation_status'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_client_phone', 'whatsapp_conversations', ['professional_id', 'client_phone'], unique=False)
    op.create_index('idx_conversations_professional_id', 'whatsapp_conversations', ['professional_id'], unique=False)
    op.create_index('idx_conversations_status', 'whatsapp_conversations', ['professional_id', 'status'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('sessions',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('recurrence_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'completed', 'cancelled', 'no_show')", name='chk_session_status'),
    sa.CheckConstraint('duration_minutes > 0', name='chk_duration'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_client_id', 'sessions', ['client_id'], unique=False)
    op.create_index('idx_sessions_conflict_check', 'sessions', ['professional_id', 'scheduled_at', 'status'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index('idx_sessions_professional_id', 'sessions', ['professional_id'], unique=False)
    op.create_index('idx_sessions_scheduled_at', 'sessions', ['professional_id', 'scheduled_at'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='chk_message_direction'),
    sa.CheckConstraint("sender_type IN ('client', 'ai', 'professional')", name='chk_message_sender_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_msg_id')
    )
    op.create_index('idx_messages_conversation_id', 'whatsapp_messages', ['conversation_id'], unique=False)

    # --- RLS policies (adicionadas manualmente — Alembic nao gera automaticamente) ---
    # Cada policy filtra linhas WHERE professional_id = current_setting(app.current_tenant)::uuid
    op.execute('ALTER TABLE clients ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON clients USING (professional_id = current_setting('app.current_tenant')::uuid)""")
    op.execute('ALTER TABLE availability_slots ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON availability_slots USING (professional_id = current_setting('app.current_tenant')::uuid)""")
    op.execute('ALTER TABLE blocked_periods ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON blocked_periods USING (professional_id = current_setting('app.current_tenant')::uuid)""")
    op.execute('ALTER TABLE recurrences ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON recurrences USING (professional_id = current_setting('app.current_tenant')::uuid)""")
    op.execute('ALTER TABLE whatsapp_conversations ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON whatsapp_conversations USING (professional_id = current_setting('app.current_tenant')::uuid)""")
    op.execute('ALTER TABLE sessions ENABLE ROW LEVEL SECURITY')
    op.execute("""CREATE POLICY tenant_isolation ON sessions USING (professional_id = current_setting('app.current_tenant')::uuid)""")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Remover RLS antes de dropar tabelas ---
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON sessions')
    op.execute('ALTER TABLE sessions DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON whatsapp_conversations')
    op.execute('ALTER TABLE whatsapp_conversations DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON recurrences')
    op.execute('ALTER TABLE recurrences DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON blocked_periods')
    op.execute('ALTER TABLE blocked_periods DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON availability_slots')
    op.execute('ALTER TABLE availability_slots DISABLE ROW LEVEL SECURITY')
    op.execute('DROP POLICY IF EXISTS tenant_isolation ON clients')
    op.execute('ALTER TABLE clients DISABLE ROW LEVEL SECURITY')

    op.drop_index('idx_messages_conversation_id', table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index('idx_sessions_scheduled_at', table_name='sessions')
    op.drop_index('idx_sessions_professional_id', table_name='sessions')
    op.drop_index('idx_sessions_conflict_check', table_name='sessions', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_index('idx_sessions_client_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_conversations_status', table_name='whatsapp_conversations', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('idx_conversations_professional_id', table_name='whatsapp_conversations')
    op.drop_index('idx_conversations_client_phone', table_name='whatsapp_conversations')
    op.drop_table('whatsapp_conversations')
    op.drop_index('idx_recurrences_professional_id', table_name='recurrences')
    op.drop_index('idx_recurrences_client_id', table_name='recurrences')
    op.drop_table('recurrences')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_professional_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_clients_professional_id', table_name='clients')
    op.drop_index('idx_clients_phone', table_name='clients')
    op.drop_table('clients')
    op.drop_index('idx_blocked_periods_range', table_name='blocked_periods')
    op.drop_index('idx_blocked_periods_professional_id', table_name='blocked_periods')
    op.drop_table('blocked_periods')
    op.drop_index('idx_availability_slots_professional_id', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_audit_logs_professional_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_professionals_email'), table_name='professionals')
    op.drop_table('professionals')
    # ### end Alembic commands ###
